### ISSUE TITLE
An error while installing mod vladimirui and merging file's.

### ISSUE THREAD

**Issue by Arathorne** [Systemcluster/The-Witcher-3-Mod-manager#42] opened 2023-09-01 18:12 UTC
Hello, this is a duplicate of a problem with installing a mod VladimirUI
**_The most part is with the winerror5, and not extracting the files_**
> Hello, whatever i try, something in here just keeps not merging and wont start the game,
the code from game
`Error [mod0000_mergedfiles]game\gui\menus\mapmenu.ws(1504): Found unexpected '}'`

and in merger those mods are present:
*InterfaceAnimations
*FastTravelFromAnywhere
![obraz](https://cdn.discordapp.com/attachments/732340985568428073/1146946575336210455/obraz.png)
AND in kdiff those two errors are present:
1
![obraz](https://cdn.discordapp.com/attachments/732340985568428073/1146946575545942016/obraz.png)
2
![obraz](https://cdn.discordapp.com/attachments/732340985568428073/1146946575764041779/obraz.png)

**+Whenever i try to instal or uninstall it give's me this message**
![obraz](https://cdn.discordapp.com/attachments/732340985568428073/1146950320094724118/obraz.png)
![obraz](https://cdn.discordapp.com/attachments/732340985568428073/1147233393952706580/obraz.png)
**_Its first time something like this is happening to me, and i dont know how to fix this, help much appreciated~!_**

**Comment by Systemcluster** [comment] 2024-07-14 03:08
I can't access the screenshots, but from `winerror5` I assume it was caused by missing write access to the game directory.

This has been a while and it's not really a mod manager but rather a script merging issue, so I'll close this here.

**Closed as completed by Systemcluster** 2024-07-14 03:08 UTC
Labels: question
